analytics:
  google: UA-33506355-1
color:
  brandColors:
    - '#ffff00'
    - '#000000'
    - '#bebe00'
    - '#565600'
    - '#8a8a00'
  brandStrength: 0.673423
  lightness: 0.341216
  rhythmicContrast: 0.314189
  saturation: 0.650777
cta: {}
layout_spectrum: 0.05351
name: McCannSports
opengraph: {}
purpose: []
typography_spectrum: 0.26414
