analytics:
  google: UA-33506355-1
color:
  brandColors:
    - '#FFFF00'
    - '#000000'
    - '#BEBE00'
    - '#565600'
    - '#8A8A00'
  brandStrength: 0.16554
  lightness: 0.341216
  rhythmicContrast: 0.314189
  saturation: 0.650777
cta: {}
layout_spectrum: 0
name: McCannSports
opengraph: {}
purpose: []
typography_spectrum: 0.292792
